const { GoogleGenAI } = require('@google/genai')
const z = require('zod')
const { zodToJsonSchema } = require("zod-to-json-schema")
const puppeteer = require('puppeteer')

const ai = new GoogleGenAI({
    apiKey: process.env.GOOGLE_GENAI_API_KEY
})

const interviewReportSchema = z.object({
    title: z.string().describe("The title of the job for which the interview report is generated"),
    matchScore: z.number().describe("A score between 0 and 100 indicating how well the candidate's profile matches the job description"),
    technicalQuestions: z.array(z.string()).describe("Technical questions that can be asked in the interview"),
    behavioralQuestions: z.array(z.string()).describe("Behavioral questions that can be asked in the interview"),
    skillGaps: z.array(z.string()).describe("List of skill gaps in the candidate's profile"),
    preparationPlan: z.array(z.string()).describe("A preparation plan broken into simple steps or topics"),
})


async function generateInterviewReport({ resume, selfDescription, jobDescription }) {

    const prompt = `
Generate an interview report.

Return ONLY valid JSON.

Follow this structure EXACTLY:

{
  "title": "Junior MERN Developer Interview Report",
  "matchScore": 90,
  "technicalQuestions": ["Explain JWT Authentication", "Describe REST API best practices"],
  "behavioralQuestions": ["Tell me about a challenge", "Describe a time you worked on a team"],
  "skillGaps": ["Testing", "System design"],
  "preparationPlan": ["Review React hooks", "Practice data structure problems"]
}

IMPORTANT:
-Change the data according to the provided resume, self description and job descriptionl
- technicalQuestions must be an array of strings
- behavioralQuestions must be an array of strings
- skillGaps must be an array of strings
- preparationPlan must be an array of strings
- Do not return arrays of objects
- Return only JSON

Resume:
${resume}

Self Description:
${selfDescription}

Job Description:
${jobDescription}
`

    const response = await ai.models.generateContent({
        model: "gemini-2.5-flash",
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            responseSchema: zodToJsonSchema(interviewReportSchema),
        }
    });

    console.log("RAW AI RESPONSE:");
    console.log(response.text);

    const parsed = JSON.parse(response.text);

    const result = interviewReportSchema.safeParse(parsed);

    if (!result.success) {
        console.log("ZOD VALIDATION ERROR:");
        console.log(result.error.format());
        console.log(JSON.stringify(result.error.issues, null, 2))
        throw new Error("AI returned invalid format");
    }

    return result.data;

}

async function generatePdfFromHtml(htmlContent) {
    const browser = await puppeteer.launch()
    const page = await browser.newPage();
    await page.setContent(htmlContent, { waitUntil: "networkidle0" })

    const pdfBuffer = await page.pdf({
        format: "A4", margin: {
            top: "20mm",
            bottom: "20mm",
            left: "15mm",
            right: "15mm"
        }
    })

    await browser.close()

    return pdfBuffer
}

async function generateResumePdf({ resume, selfDescription, jobDescription }) {

    const resumePdfSchema = z.object({
        html: z.string().describe("The HTML content of the resume which can be converted to PDF using any library like puppeteer")
    })

    const prompt = `Generate resume for a candidate with the following details:
                        Resume: ${resume}
                        Self Description: ${selfDescription}
                        Job Description: ${jobDescription}

                        the response should be a JSON object with a single field "html" which contains the HTML content of the resume which can be converted to PDF using any library like puppeteer.
                        The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience. The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
                        The content of resume should be not sound like it's generated by AI and should be as close as possible to a real human-written resume.
                        you can highlight the content using some colors or different font styles but the overall design should be simple and professional.
                        The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
                        The resume should not be so lengthy, it should ideally be 1-2 pages long when converted to PDF. Focus on quality rather than quantity and make sure to include all the relevant information that can increase the candidate's chances of getting an interview call for the given job description.
                    `

    const response = await ai.models.generateContent({
        model: "gemini-2.5-flash",
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            responseSchema: zodToJsonSchema(resumePdfSchema),
        }
    })
    const jsonContent = JSON.parse(response.text)
    const pdfBuffer = await generatePdfFromHtml(jsonContent.html)
    return pdfBuffer
}

module.exports = {
    generateInterviewReport,
    generateResumePdf
}